export const SET_HOMESLIDE = "GENERAL/SET_HOMESLIDE"

export const ADD_HOMESLIDE = "GENERAL/ADD_HOMESLIDE"

export const SET_TRENDINGS = "GENERAL/SET_TRENDINGS"

export const ADD_TRENDINGS = "GENERAL/ADD_TRENDINGS"
